

- name: Create a10_slb_service_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_service_group instance
    a10_slb_service_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: sg1
      protocol: tcp
      lb_method: round-robin
      stats_data_action: stats-data-enable

- name: Update a10_slb_service_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_service_group instance
    a10_slb_service_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: sg1
      protocol: tcp
      lb_method: round-robin
      stats_data_action: stats-data-enable

- name: Delete a10_slb_service_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_service_group instance
    a10_slb_service_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: sg1
      protocol: tcp
      lb_method: round-robin
      stats_data_action: stats-data-enable