

- name: Create a10_slb_virtual_server_port_stats_cache example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_virtual_server_port_stats_cache instance
    a10_slb_virtual_server_port_stats_cache:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_port

- name: Update a10_slb_virtual_server_port_stats_cache example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_virtual_server_port_stats_cache instance
    a10_slb_virtual_server_port_stats_cache:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_port

- name: Delete a10_slb_virtual_server_port_stats_cache example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_virtual_server_port_stats_cache instance
    a10_slb_virtual_server_port_stats_cache:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_port