

- name: Create a10_slb_server_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_server_port instance
    a10_slb_server_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      port_number: 0
      protocol: tcp
      template_port: default
      action: enable
      weight: 1
      conn_limit: 1
      stats_data_action: stats-data-enable

- name: Update a10_slb_server_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_server_port instance
    a10_slb_server_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      port_number: 0
      protocol: tcp
      template_port: default
      action: enable
      weight: 1
      conn_limit: 1
      stats_data_action: stats-data-enable

- name: Delete a10_slb_server_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_server_port instance
    a10_slb_server_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      port_number: 0
      protocol: tcp
      template_port: default
      action: enable
      weight: 1
      conn_limit: 1
      stats_data_action: stats-data-enable