

- name: Create a10_slb_common_conn_rate_limit_src_ip example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_common_conn_rate_limit_src_ip instance
    a10_slb_common_conn_rate_limit_src_ip:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      protocol: tcp

- name: Update a10_slb_common_conn_rate_limit_src_ip example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_common_conn_rate_limit_src_ip instance
    a10_slb_common_conn_rate_limit_src_ip:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      protocol: tcp

- name: Delete a10_slb_common_conn_rate_limit_src_ip example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_common_conn_rate_limit_src_ip instance
    a10_slb_common_conn_rate_limit_src_ip:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      protocol: tcp